## -------------Actuator--------------
info:
  app:
    name: spring-web-scaffold
    version: 1.2.8
management:
#  endpoint:
#    beans:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
## -----------------------------------

server:
  port: 8999
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: zack2go
logging:
  level:
    root: DEBUG
  logging.file: rest-web.log

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
